[package]
name = "edgefirst-gbm-sys"
version = "0.4.1"
authors = [
    "Victoria Brekenfeld <github@drakulix.de>",
    "Au-Zone Technologies <support@au-zone.com>",
]
build = "build.rs"
description = "Bindgen generated unsafe libgbm wrapper with dynamic loading support"
documentation = "https://docs.rs/edgefirst-gbm-sys"
repository = "https://github.com/EdgeFirstAI/gbm.rs"
keywords = ["gbm", "bindings", "dynamic-loading"]
categories = ["external-ffi-bindings"]
license = "MIT"
edition = "2021"
readme = "../README.md"

[lib]
path = "src/lib.rs"

[build-dependencies.bindgen]
version = "0.72"
optional = true

[dependencies.libloading]
version = "0.8"
optional = true

# Specify version of bindgen deps to fix `check-minimal` test
[build-dependencies]
proc-macro2 = { version = "1.0.69", optional = true }
regex = { version = "1.10", optional = true }

[dependencies]
libc = "0.2"

[features]
use_bindgen = ["bindgen", "dep:proc-macro2", "dep:regex"]
update_bindings = ["use_bindgen"]
dynamic = ["dep:libloading"]
